### ISSUE TITLE
Bluebird.map

### ISSUE THREAD

**Issue by j3bb9z** [seongjin605/arehs#1]
Hi, 

Thanks for sharing your solution.

However, did you check existing libraries before creating this one? 
I think Bluebird.map exists for more than 7 years with concurrency param:
http://bluebirdjs.com/docs/api/promise.map.html#map-option-concurrency

Does your solution add any value over that?

Not trying to be mean or anything. Just asking some genuine questions.

**Comment by seongjin605** [comment]
Hi @j3bb9z,

First of all, thank you for your interest.

I am answering your question. 
I did a benchmarking with `arehs`, `bluebird`, and `promise.all` doing chunk processing with 50 chunks based on 1000 records and the result was that arehs performed the best as shown below.

However, there was no significant performance difference between arehs and `promise.map`.
Also, I think the results may vary depending on the environment and various situations. 
However, arehs is built for chunk processing in many batches, and bluebird offers more options.
However, bluebird is a fairly large library compared to other promises, and we believe that the cost of large dependencies can increase, affecting bundle size and initial loading time.
Consider it accordingly based on your situation.

Again, thank you for your interest! 

```javascript
const { Arehs } = require("arehs");
const BlueBird = require('bluebird');


const delay = (i) => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res(i);
    }, 150 + Math.random() * 1000);
  });
};

const tasks = Array.from({ length: 1000 }).map((d, i) => i);
(async () => {

  const startArehs = performance.now();
  await Arehs.create(tasks).withConcurrency(50).mapAsync(delay);
  const endArehs = performance.now();

  console.log(`Arehs: ${endArehs - startArehs}ms`);

  const startPromiseAll = performance.now();
  while (tasks.length > 0) {
    const chunkedTasks = tasks.splice(0, 50);
    await Promise.all(chunkedTasks.map(delay));
  }
  const endPromiseAll = performance.now();

  console.log(`Promise.all: ${endPromiseAll - startPromiseAll}ms`);
})();

function promiseMap() {
    const startBluebird = performance.now();
    BlueBird.map(tasks, delay, { concurrency: 50 }).then(results => {
      const endBlueBird = performance.now();
      console.log(`BlueBird Map: ${endBlueBird - startBluebird}ms`);
    })
    .catch(error => {
      console.error('An error occurred:', error);
    });
}
promiseMap();
```

![image](https://github.com/seongjin605/arehs/assets/16683075/472a2167-7274-4804-92fb-26ac454bbd91)
